### PR TITLE
Modified redirect_uri comparison method in authorization flow, and others

### PR DESCRIPTION
**Pull request by DawoonC**
- modified redirect_uri comparison method in authorization flow
- added parsing client credentials from request body in token flow
- added renewing refresh token when refreshing access token
- added removeByRefreshToken method for revoking token in refreshing flow
- implemented test methods accordingly and fixed some typo

### CODE REVIEW

**Comment by pablodgonzalez** [comment]
Hi Dawoon, the RFC (http://tools.ietf.org/html/rfc6749#page-10) indicate to the refresh_token flow, the new refresh_token is optional. Can you add a configuration attribute?

**Comment by pablodgonzalez** [comment]
Hi Dawoon sorry,I add more, for redirect_uri the RFC defines that redirect_uri must no have fragment component, and must retain query parameters (specially the state parameter to do the security check by the client).
So, is good correcting the comparison redirect_uri, but we going to open other issues.
Can you add the checking for fragments on redirect_uri and open a new issue for retaining query parameters?

**Comment by DawoonC** [comment]
Hi Pablo, thanks for the comments! I was able to learn more about the OAuth 2.0 :)
I've added things you mentioned and tested with both test code and my hand.
However, it seems that the query parameters are retained correctly as it is now. I tested authorization flow with adding "state" parameter, and it was retained correctly through out the flow.

**Comment by t1msh** [comment]
Hi
Thank you for your contribution guys, going to merge it as soon as i get to my laptop (in 1 day i hope)

**Pull request merged**
